### ISSUE TITLE
RenameStream

### ISSUE THREAD

**Issue by bartvm** [bartvm/fuel#12]
From https://github.com/bartvm/blocks/issues/267

Something that @arasmus ran into: When combining multiple data streams, the names of the sources might clash. I guess a general solution for this would be to create a `RenameStream` which just renames the sources and passes on the data directly. That way you can put than into the yet-to-be-written data stream-chainer.

**Comment by vdumoulin** [comment]
@Thrandis this is your ticket for this week.
