### ISSUE TITLE
A Scheme to Iterate over Single Examples

### ISSUE THREAD

**Issue by rizar** [bartvm/fuel#19]
It is currently impossible to iterate over MNIST examples, not batches of examples.

Even `SequentialScheme(num_examples, 1)` does not fill this gap, because the requests it provides are singleton lists.

I would solve that by adding a new scheme, let's say `ExamplesScheme`, whose requests would be integers, not lists.

**Comment by dwf** [comment]
Why would you want singletons rather than batch size 1?

**Comment by rizar** [comment]
It find it much more convenient to write preprocessing for this format. Otherwise every preprocessing wrapper that I have must first unpack the batch and in the end pack the batch back.

**Comment by bartvm** [comment]
Fixed in #20.
