### ISSUE TITLE
Rename `DataStreamWrapper` to `Transformer`

### ISSUE THREAD

**Issue by bartvm** [bartvm/fuel#23]
`DataStreamWrapper` made sense when we were designing this, because the point was that data streams and data streams wrappers share the same interface. (Initially we actually tried making them one and the same class, but that ended up not happening, and now they just share a base class.)

The problem with `DataStreamWrapper` is that it's a bit obscure of a name, and I think it actually confuses people sometimes, because they're not sure what the difference between `DataStream` and `DataStreamWrapper` is. I actually like Pylearn2's `Transformer` better. Another alternative is `Preprocessor`, but that sounds too much like just doing whitening, etc. and not routine transformations like sorting, merging, etc.

So the terminology then becomes: Instantiate a **dataset**, and create a **data stream** that reads from this dataset (potentially using a particular iteration scheme). Afterwards you can apply a series of **transformations** on the data stream (some transformers can support the `iteration_scheme` argument, some don't, but the `get_epoch_iterator` interface is the same).

Thoughts? Here I go randomly tagging people for opinions again: @rizar @lamblin @vdumoulin @laurent-dinh @dwf @pbrakel @jbornschein

**Comment by lamblin** [comment]
`Transformer` sounds great to me for these on-the-fly transformations.
`Preprocessor` could be used for processing that is done once (then stored) on the data, beforehand, outside of the training script.

**Comment by jbornschein** [comment]
I agree. Transformer seems to be a much better name than than
DataStreamWrapper and more suited than Preprocessig.

+1 for that change from my side.

**Comment by rizar** [comment]
Works for me!

**Comment by vdumoulin** [comment]
You have my vote.
