### ISSUE TITLE
I got a crashing (Blocks) MNIST tutorial using float32 and GPU

### ISSUE THREAD

**Issue by EderSantana** [bartvm/fuel#24]
When setting ~/.theanorc floatX=float32 and device=gpu, I couldn't run the Blocks MNIST tutorial. I thought that Fuel could check theano.config.floatX and serve downcasted when necessary.

**Comment by bartvm** [comment]
Well, the idea is that Fuel doesn't have any dependencies on floatX, which is why it has its own, separate `floatX` configuration. However, I guess it's reasonable to use Theano's floatX if Theano is installed. Fixed in  2941829.
