### ISSUE TITLE
configparser instead of pyyaml?

### ISSUE THREAD

**Issue by jbornschein** [bartvm/fuel#25]
Just wondering: It seems your requirements for configuration-file parsing are not very high. Maybe it would be sufficient to use https://docs.python.org/2/library/configparser.html  ?

Pros: it's part of the std. lib for Python 2 and 3 
Cons: a) it's Windows-INI style syntax; b) arguably less powerful than YAML.

**Comment by dwf** [comment]
I imagine the thinking is that pyyaml is more futureproof?

**Comment by bartvm** [comment]
It's actually just that I don't like that syntax as much :p and the
possibility to configure lists, dicts, etc. if needed, but it's worth
considering. Another alternative could be JSON? That's built in

**Comment by jbornschein** [comment]
But not supporting lists and dicts is indeed a major drawback.

Not sure if JSON is a preferable .config file syntax -- seems strings always need quotes around them, even when when used keys for configuration values. It's also not so nice that the whole config file would need an opening and a closing bracket. Although that restriction could be easily lifted by just  automatically adding a "{" at the beginning, and a "}" at the end. 

Anyway -- maybe it's just not worth the trouble changin anything.

**Comment by bartvm** [comment]
Ah, didn't think about the quotes. Then yeah, I guess I prefer sticking
with YAML

**Comment by rizar** [comment]
+1, ini files are ghosts from 90s!
