### ISSUE TITLE
Factor out common logic MNIST, CIFAR-10 and similar datasets

### ISSUE THREAD

**Issue by bartvm** [bartvm/fuel#3]
Further to my comment at #2, things that should probably be factored out:

- [ ] **Finding files**

All datasets that load files have similar logic: They concatenate the `FUEL_DATA_PATH` with the name of the folder in which the dataset is stored, and with the name of the file that we want to read. This should probably be factored out into a `get_path()` method which can be part of a mix-in `DataFiles` class or something. This can also raise a custom error with information on how to set the data path in the configuration.

- [x] **Start/stop**

This one might be a bit trickier, but should probably be factored out into a mix-in class as well so that every dataset that is loaded into memory can simply use this mixin class to support the `start` and `stop` arguments.

- [x] **In-memory datasets**

Maybe this could be combined with the current `InMemoryDataset` class, or maybe we could factor it out into a separate class, but the logic of raising an error when the state is not `None` and simply returning the indices of the data could also be factored out, because it will be needed for any dataset whose `get_data` logic is basically just indexing.

- [ ] **Flattening**

The datasets should probably just return the original images, and we should have a flattening stream that does the flattening batch-wise.

**Comment by vdumoulin** [comment]
Regarding flattening, here's my idea: we already have most of what we need in `DataStreamMapping`, we just need a subclass which implements it in a user-friendly way.

The interface I'm thinking of looks like this:

```python
class DataStreamFlattener(DataStreamMapping):
    """Flattens user-selected sources of the wrapped data stream.

    If a source has zero or one dimension, nothing is done, otherwise the
    source is flattened for all but the first axis.
    
    Parameters
    ----------
    sources_to_flatten : tuple of str
        Sources to flatten
    """
```

Internally, a `flatten` method is implemented to do the mapping, and that method is what is passed to `DataStreamWrapper`'s constructor.

The same principle could be applied to cast sources into other dtypes:

```python
class DataStreamCaster(DataStreamMapping):
    """Casts user-selected sources of the wrapped data stream into other dtypes.
    
    Parameters
    ----------
    sources_to_cast : dict mapping str to str
        Dictionary mapping sources to their desired dtype.
    """
```

**Comment by bartvm** [comment]
Great idea, I guess that many data streams wrappers can actually inherit from `DataStreamMapping`

**Comment by vdumoulin** [comment]
@bartvm Do you feel like this issue has been fixed by recent pull requests?

**Comment by bartvm** [comment]
Yes, MNIST and CIFAR-10 look a lot more minimal now, much better.
