### ISSUE TITLE
from Pylearn2 SequenceDataset to Fuel

### ISSUE THREAD

**Issue by EderSantana** [bartvm/fuel#36]
I'm trying to test Blocks RNNs, and I think the markov chain example is a little bit hard to read. I can understand the RNN bricks though. I wish I could know what is the easiest/right way to translate Pylearn2 datasets to Fuel datasets? More specifically, I have a ```pylearn2.VectorSpaceDataset``` based on ```pylearn2.SequenceDataSpace``` and I wish I could use it with Blocks. Also, the dataset iterator is reading from a HDF5 file and swapping the axis to make time the first dimension. How can I just wrap this dataset with a Fuel class and throw it to ```blocks.DataStream```?

Do you have any guidelines for doing so?

**Comment by bartvm** [comment]
For simpler examples of RNNs be sure to have a look at https://github.com/bartvm/blocks/pull/325 and at [the new documentation](http://blocks.readthedocs.org/en/latest/rnn.html).

There is currently no written documentation on how to use Pylearn2 datasets easily. There might be wrappers in the future though (@lamblin?).

I don't have time to try it out right now, but I imagine the following, relatively straightforward method, would work:

* Create a `Pylearn2Dataset` class. This dataset class should call the Pylearn2's `Dataset.iterator` method with the relevant arguments in its `open` method, and return this as a state.
* The `get_data` method in the Fuel `Dataset` should then simply contain `return next(state)`.
* Now you can call `DataStream(Pylearn2Dataset(...))`, and it should work just fine.

**Comment by EderSantana** [comment]
Awesome, what you suggested seems to work fine.

**Comment by EderSantana** [comment]
sample solution: EderSantana/blocks_contrib/pylear2fuel/\_\_init\_\_.py
