### ISSUE TITLE
Subset MNIST

### ISSUE THREAD

**Issue by AjayTalati** [bartvm/fuel#49]
Hi,

I'd like to run an experiment using a subset of the binarized MNIST 28 dataset.

I just want to run some quick experiments using say the first 12,000 images. 

How do I do that?

Thanks,

Aj

**Comment by vdumoulin** [comment]
The documentation is a bit lacking at the moment, but `BinarizedMNIST` inherits from `IndexableDataset`, which has `start` and `stop` constructor arguments (see [here](https://github.com/bartvm/fuel/blob/master/fuel/datasets/base.py#L294)) that you can use to select a subset of some split.

For instance,
```python
train_set_subset = BinarizedMNIST(which_set='train', start=0, stop=12000)
```
would load the first 12,000 images of the training set.

**Comment by AjayTalati** [comment]
Hey Vincent,

thanks for the quick reply - so I'm experimenting with Jorg's DRAW implementation, but I only want do quick experiments, 

I guess the places the datastreams are set are lines 194-196?

https://github.com/jbornschein/draw/blob/master/draw/train-draw.py#L194

Sorry I'm new to FUEL and BLOCKS

**Comment by vdumoulin** [comment]
In that specific case, you can either set the `start` and `stop` constructor arguments in lines 194-196 or change the first argument of the `SequentialScheme` constructor in lines 198-200 to something other than `mnist_{train,valid,test}.num_examples`, _e.g._ 5000.

I just created a Google Group for Fuel [here](https://groups.google.com/d/forum/fuel-users). I'll close this issue, but I'll be happy to answer other questions you might have through the Google Group.
