### ISSUE TITLE
Create a google group for fuel users

### ISSUE THREAD

**Issue by vdumoulin** [bartvm/fuel#50]
This would allow people to ask questions without opening issues.

**Comment by AjayTalati** [comment]
That would certainly help people new to the `BLOCKS + FUEL` framework, and attract more users :+1:

**Comment by vdumoulin** [comment]
Closing via https://groups.google.com/d/forum/fuel-users

**Comment by bartvm** [comment]
Thanks! We'll need to add it to the README and docs too.

**Comment by vdumoulin** [comment]
@bartvm see #51.
