### ISSUE TITLE
progressbar for long-running converters?

### ISSUE THREAD

**Issue by dwf** [bartvm/fuel#70]
I'm thinking it would be nice to display a progress bar when doing a super-long conversion, but I don't like the idea of littering the converter code itself with calls to progressbar.

One possibility is using the 'extra' dictionary on LogRecords and installing a custom handler in fuel-convert. That way it's just passed as usable metadata in regular logging calls and fuel-convert (or any other client) can use it as it likes. This seems fairly clean. Any thoughts?

**Comment by dwf** [comment]
For reference, [here's the explanation of the 'extra' functionality for the logger](https://docs.python.org/2/library/logging.html#logging.Logger.debug).

**Comment by vdumoulin** [comment]
That's a great idea. It could also be useful for downloaders.

**Comment by bartvm** [comment]
:+1:

**Comment by dwf** [comment]
Alright, yeah, I was surprised the people who wrote the logging module thought ahead this far.

I guess my thinking would be to make progressbar-like messages DEBUG level.
