### ISSUE TITLE
Pylearn2 wrapper?

### ISSUE THREAD

**Issue by jstaker7** [bartvm/fuel#81]
(Sorry if creating a new issue is not the best way to communicate ... is there a preferred method?)

I have been working in pylearn2 for some time now and I am experiencing frustration in its limitations regarding hdf5 datasets. I'm very interested in using fuel for managing my datasets and I was excited to see in the documentation that there is a future direction to integrate fuel and pylearn2. However, I'm a little impatient to start taking advantage of fuel :).

Do you have any recommendations or prototypes towards pylearn2 integration? Seems like communication through the pylearn2 iterator is key. I started to hole-fill the fuel H5PYDataset so that it implemented a pylearn2-capable iterator, but it's turning out to be a big job and I'm not 100% sure that it's the right direction. At this point I'd like to hear your thoughts before I start cowboy coding a fork. I looked in the branches/forks and didn't immediately find anything relevant. Thanks!

**Comment by dwf** [comment]
See ticket #77. So far it's still in the planning stages.

**Comment by jstaker7** [comment]
Hadn't refreshed my page, so I missed that issue before I posted. Thanks again!
