### ISSUE TITLE
H5PYDataset lost split data if not load_in_memory

### ISSUE THREAD

**Issue by bobogei81123** [bartvm/fuel#92]
I followed the tutorial [here](https://github.com/bartvm/fuel/blob/master/docs/new_dataset.rst) to create a custom dataset. But when loading data using `H5PYDataset`,  some of the data seems to be lost when there is a split array.

Here is an example. 
https://gist.github.com/bobogei81123/6a2d93caa6f809526e4f
It seems like setting `load_in_memory=True` could solve the problem.
(Also, ShuffleScheme won't work if `load_in_memory=False`)

**Comment by vdumoulin** [comment]
Thanks for pointing it out. It was indeed a bug.

We are already aware that `H5PYDataset` doesn't work well with `ShuffledScheme` (see #91 for the fix). I included a fix for your issue as part of that PR.

**Comment by vdumoulin** [comment]
Fixed by #91. Thanks again!
